version: '3.8'

services:
  mongo:
    image: mongo
    container_name: mongo_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  agente-ai:
    build: .
    container_name: agente_ai
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
      - OPENAI_API_KEY=sua-chave-api-aqui

volumes:
  mongo_data:
